### ISSUE TITLE
Labels and help texts cant be loaded in deployed version

### ISSUE THREAD

**Issue by oBlissing** [libris/kitin#257]

**Comment by niklasl** [comment]
Changes to terms (as all of def-data) are updated as regular data – i.e. PUT to the relevant whelk via the load_defs_whelk.sh script in the libris/definitions repo. Since this script does not authenticate itself, protected whelks can only be accessed locally, or using a tunnel. Example of loading the terms against a whelk (tunneled to via 8890):

    scripts/load_defs_whelk.sh http://localhost:9980/whelk terms
